# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
