# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0006_auto_20170908_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
