# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='handles',
            name='codechef_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='handles',
            name='hacker_earth_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='handles',
            name='hacker_rank_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='handles',
            name='spoj_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
