# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170908_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handles',
            name='username',
        ),
        migrations.DeleteModel(
            name='Handles',
        ),
    ]
