# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170908_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codechef_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hacker_earth_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hacker_rank_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='spoj_rating',
            field=models.IntegerField(default=0),
        ),
    ]
