# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171013_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
