# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171119_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codechef_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hacker_earth_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spoj_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
