# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AID', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=7)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(default='', max_length=6)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QID', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=7)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(default='', max_length=6)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='QID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Question'),
        ),
    ]
