# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20170414_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QID',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
