# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20170414_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='AID',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(default='', max_length=1055),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=1055),
        ),
    ]
