# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20170707_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('QAID', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='AID',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='QID',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=set([('QAID', 'username')]),
        ),
    ]
