# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_auto_20170708_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
