# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0009_vote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='AID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.Answer'),
        ),
        migrations.AddField(
            model_name='vote',
            name='QID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='QAID',
        ),
    ]
