# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_auto_20170708_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='AID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.Answer'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='QID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.Question'),
        ),
    ]
