# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0013_auto_20170708_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-AID', '-QID']},
        ),
    ]
