# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0017_auto_20170713_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
