# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0018_auto_20170721_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='AID',
        ),
        migrations.RemoveField(
            model_name='question',
            name='QID',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
